Fix compilation warning caused by missing semicolons
```
error: trailing semicolon in macro used in expression position
   --> src/tasks.rs:157:5
    |
157 |     bail!("nRF52840 USB device not found")
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: macro invocations at the end of a block are treated as expressions
    = note: to ignore the value produced by the macro, add a semicolon after the invocation of `bail`
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
    = note: this error originates in the macro `bail` (in Nightly builds, run with -Z macro-backtrace for more info)
```